import copy
from dataclasses import dataclass
from typing import Any

import torch
import torch.utils._pytree as pytree
from torch._library.fake_class_registry import FakeScriptObject
from torch._library.opaque_object import is_custom_class
from torch.fx.node import Target


# Below is an implementation of generating FunctionSchema from example values.
# This is helpful for generating FunctionSchema for HigherOrderOperator, where
# we don't have a function to inspect and each call of the higher order operator
# would have different schema.
@dataclass(frozen=True, slots=True)
class HopArgumentInfo:
    # Could give a name to the operand by default it's empty string.
    name: str
    example_value: Any
    # Provide a default_value
    default_value: Any
    # Whether this argument gets mutated in the hop subgraph.
    # For output, this should always be False
    is_mutated: bool
    kw_only: bool


class HopArgumentInfoGen:
    @staticmethod
    def from_example(
        example_value: Any,
        *,
        name: str = "",
        default_value: Any | None = None,
        is_mutated: bool = False,
        kw_only: bool = False,
    ) -> HopArgumentInfo:
        if default_value is not None:
            if type(example_value) is not type(default_value):
                raise AssertionError(
                    f"example_value type {type(example_value)} doesn't match default_value type: {type(default_value)}"
                )

        return HopArgumentInfo(
            name=name,
            example_value=example_value,
            default_value=default_value,
            is_mutated=is_mutated,
            kw_only=kw_only,
        )


def _type_str(obj: Any) -> str:
    # The JitType python bindings no longer exist, so schemas are generated by
    # building a schema string and handing it to torch._C.parse_schema.
    if isinstance(obj, torch.Tensor):
        return "Tensor"
    if isinstance(obj, torch.SymInt):
        return "SymInt"
    if isinstance(obj, torch.SymBool):
        return "SymBool"
    if isinstance(obj, torch.SymFloat):
        return "float"
    if isinstance(obj, bool):
        return "bool"
    if isinstance(obj, int):
        return "int"
    if isinstance(obj, float):
        return "float"
    if isinstance(obj, str):
        return "str"
    if isinstance(obj, type(None)):
        return "Any"
    if isinstance(obj, (torch.fx.GraphModule, torch._ops.OperatorBase)):
        return "Any"
    if isinstance(obj, (FakeScriptObject, pytree.TreeSpec)) or is_custom_class(
        type(obj)
    ):
        # These used to map to PyObjectType, which the schema grammar cannot
        # express; Any is the closest representable type.
        return "Any"
    if isinstance(obj, list):
        if len(obj) == 0:
            raise RuntimeError(f"cannot infer element type of empty list: {obj}")
        elems = {_type_str(v) for v in obj}
        if len(elems) != 1:
            raise RuntimeError(f"list has mixed element types {elems}: {obj}")
        return f"{elems.pop()}[]"
    if isinstance(obj, tuple):
        if len(obj) == 0:
            return "()"
        return "(" + ", ".join(_type_str(v) for v in obj) + ")"
    if isinstance(obj, dict):
        if len(obj) == 0:
            raise RuntimeError(f"cannot infer element types of empty dict: {obj}")
        keys = {_type_str(k) for k in obj}
        vals = {_type_str(v) for v in obj.values()}
        if len(keys) != 1 or len(vals) != 1:
            raise RuntimeError(f"dict has mixed element types {keys}, {vals}: {obj}")
        return f"Dict({keys.pop()}, {vals.pop()})"
    raise RuntimeError(f"cannot infer schema type of {type(obj)}: {obj}")


def _default_str(value: Any) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    raise RuntimeError(
        f"schema-string generation only supports int/float/bool/str defaults, got {type(value)}"
    )


class CFunctionSchemaGen:
    """See Note: [HigherOrderOperator schema generation] below."""

    @staticmethod
    def from_hop_argument_info(
        op_name: str,
        inp_argument_info: list[HopArgumentInfo],
        out_argument_info: HopArgumentInfo,
        schema_tree_spec: pytree.TreeSpec | None,
    ) -> Any:
        if not isinstance(out_argument_info.example_value, tuple):
            raise AssertionError(
                f"expect out_argument_info's example_value to be a tuple but got {out_argument_info.example_value}"
            )
        if out_argument_info.is_mutated:
            raise AssertionError(
                "out_argument_info.is_mutated should always be set to False."
            )

        arg_strs = []
        for i, arg_info in enumerate(inp_argument_info):
            ty = _type_str(arg_info.example_value)
            if arg_info.is_mutated:
                ty = f"{ty}(a{i}!)"
            arg = f"{ty} {arg_info.name}"
            if arg_info.default_value is not None:
                arg += f"={_default_str(arg_info.default_value)}"
            arg_strs.append(arg)

        out_vals = out_argument_info.example_value
        ret_types = [_type_str(v) for v in out_vals]
        ret = ret_types[0] if len(ret_types) == 1 else "(" + ", ".join(ret_types) + ")"

        schema_str = f"{op_name}({', '.join(arg_strs)}) -> {ret}"
        try:
            parsed = torch._C.parse_schema(schema_str)
        except Exception as e:
            raise RuntimeError(f"failed to generate HOP schema {schema_str!r}: {e}") from e
        # Arguments pulled off the parsed schema carry the alias/write and
        # default information; kw_only-ness is not expressible in a schema
        # string and is dropped. Any-typed arguments are recorded by name
        # since Argument.type is not accessible from Python any more.
        any_arg_names = frozenset(
            info.name
            for info in inp_argument_info
            if _type_str(info.example_value) == "Any"
        )
        return HopSchema(
            parsed.name,
            parsed.overload_name,
            list(parsed.arguments),
            list(parsed.returns),
            False,
            False,
            schema_tree_spec,
            any_arg_names,
        )


class HopSchemaGenerator:
    def __init__(self, hop: torch._ops.HigherOrderOperator):
        self.arg_infos: list[HopArgumentInfo] = []
        self.example_outputs: list[Any] = []
        self.schema_tree_spec: pytree.TreeSpec | None = None
        self.hop = hop

    def add_arg(
        self,
        name: str,
        example_value: Any,
        default_value: Any | None = None,
        is_mutated: bool = False,
        kw_only: bool = False,
    ) -> None:
        if callable(example_value) and not is_custom_class(type(example_value)):
            if not isinstance(
                example_value, (torch.fx.GraphModule, torch._ops.OperatorBase)
            ):
                raise AssertionError(
                    "Expect callable to be a GraphModule or an OperatorBase. Please call materialize_as_graph first "
                    f"to turn callable arguments {example_value} into a GraphModule."
                )
        _, flat_spec = pytree.tree_flatten(example_value)
        if not flat_spec.is_leaf():
            raise RuntimeError(
                f"example_value {example_value} is not a leaf node. "
                "Please only add flattened inputs to the hop schema. "
                "If you need some structure in the arguments, please"
                "add_arg for flattened args one by one then "
                "call add_schema_tree_spec to register the original pytree "
                " spec of the args."
            )

        arg_info = HopArgumentInfoGen.from_example(
            example_value=example_value,
            name=name,
            default_value=default_value,
            is_mutated=is_mutated,
            kw_only=kw_only,
        )
        self.arg_infos.append(arg_info)

    def add_output(self, output: Any) -> None:
        self.example_outputs.append(output)

    def add_schema_tree_spec(self, *args: Any, **kwargs: Any) -> None:
        """schema tree spec is the tree spec from flattening all inputs to the hop with pytree.tree_flatten
        Since torch.FunctionSchema only have proper mutation/alias support for flattened inputs, we need
        to store the tree spec in order to reconstruct the inputs to the hop.
        """
        self.schema_tree_spec = pytree.tree_flatten((args, kwargs))[1]

    def gen_schema(self) -> torch._C.FunctionSchema:
        for i, arg_info in enumerate(self.arg_infos):
            arg_spec = pytree.tree_flatten(arg_info.example_value)[1]
            if not arg_spec.is_leaf() and self.schema_tree_spec is None:
                raise RuntimeError(
                    f"example_value of arg_infos[{i}] is {arg_info.example_value}, which is not a leaf node. "
                    "Please call add_schema_tree_spec to add a schema tree spec first. "
                    "Or consider changing the hop's signature to only take flattened arguments."
                )

        return CFunctionSchemaGen.from_hop_argument_info(
            str(self.hop),
            self.arg_infos,
            HopArgumentInfoGen.from_example(tuple(self.example_outputs), name="out"),
            self.schema_tree_spec,
        )


class HopSchema(torch._C.FunctionSchema):
    def __init__(
        self,
        name: str,
        overload_name: str,
        arguments: list[torch._C.Argument],
        returns: list[torch._C.Argument],
        is_vararg: bool,
        is_varret: bool,
        schema_tree_spec: pytree.TreeSpec | None,
        any_arg_names: frozenset[str] = frozenset(),
    ):
        self.tree_spec = schema_tree_spec
        self.is_vararg = is_vararg
        self.is_varret = is_varret
        self.any_arg_names = any_arg_names
        super().__init__(
            name,
            overload_name,
            arguments,
            returns,
            self.is_vararg,
            self.is_varret,
        )

    def __deepcopy__(self, memo: Any) -> "HopSchema":
        # Need to additionally copy the tree_spec since
        # it's not a member of torch._C.FunctionSchema
        return HopSchema(
            self.name,
            self.overload_name,
            self.arguments,
            self.returns,
            self.is_vararg,
            self.is_varret,
            copy.deepcopy(self.tree_spec),
            self.any_arg_names,
        )


def find_hop_schema(
    gm: torch.fx.GraphModule, target: Target
) -> list[torch._C.FunctionSchema]:
    schemas = []
    for node in gm.graph.find_nodes(op="call_function", target=target):

        def _get_example_value(node: torch.fx.Node) -> Any:
            if node.op == "get_attr":
                if not isinstance(node.target, str):
                    raise AssertionError(
                        f"expected node.target to be str for get_attr, got {type(node.target)}"
                    )
                return getattr(gm, node.target)
            else:
                return (
                    node.meta["example_value"]
                    if "example_value" in node.meta
                    else node.meta["val"]
                )

        fake_args, fake_kwargs = pytree.tree_map_only(
            torch.fx.Node,
            _get_example_value,
            (node.args, node.kwargs),
        )
        schema = node.target.gen_schema(*fake_args, **fake_kwargs)
        schemas.append(schema)
    return schemas
