# Paths and helpers for the out-of-place PyTorch ROCm hipify tree.

set(PYTORCH_HIPIFY_DIR "${PROJECT_SOURCE_DIR}/build/hipify" CACHE PATH
    "Directory containing sources generated by tools/amd_build/build_amd.py")
get_filename_component(PYTORCH_HIPIFY_DIR "${PYTORCH_HIPIFY_DIR}" ABSOLUTE)

if(USE_ROCM)
  if(NOT EXISTS "${PYTORCH_HIPIFY_DIR}/.pytorch-hipify.json")
    message(FATAL_ERROR
      "ROCm hipify output was not found at ${PYTORCH_HIPIFY_DIR}. "
      "Run tools/amd_build/build_amd.py before configuring PyTorch, or set "
      "PYTORCH_HIPIFY_DIR to an explicitly generated output directory.")
  endif()

  set(PYTORCH_HIPIFY_TORCH_DIR "${PYTORCH_HIPIFY_DIR}/torch")
  set(PYTORCH_HIPIFY_ATEN_DIR "${PYTORCH_HIPIFY_DIR}/aten/src/ATen")

  function(pytorch_hipify_source_list output_var)
    set(_hipified_sources)
    foreach(_source IN LISTS ARGN)
      if(IS_ABSOLUTE "${_source}")
        file(RELATIVE_PATH _relative_source "${PROJECT_SOURCE_DIR}" "${_source}")
        if(NOT _relative_source MATCHES "^\\.\\.")
          set(_hipified_source "${PYTORCH_HIPIFY_DIR}/${_relative_source}")
          if(EXISTS "${_hipified_source}")
            list(APPEND _hipified_sources "${_hipified_source}")
            continue()
          endif()
        endif()
      endif()
      list(APPEND _hipified_sources "${_source}")
    endforeach()
    set(${output_var} "${_hipified_sources}" PARENT_SCOPE)
  endfunction()

  function(pytorch_hipify_generated_source_list output_var)
    set(_hipified_sources)
    foreach(_source IN LISTS ARGN)
      string(REPLACE
        "${PROJECT_SOURCE_DIR}/torch/"
        "${PYTORCH_HIPIFY_TORCH_DIR}/"
        _hipified_source
        "${_source}")
      list(APPEND _hipified_sources "${_hipified_source}")
    endforeach()
    set(${output_var} "${_hipified_sources}" PARENT_SCOPE)
  endfunction()
endif()
