# Owner(s): ["oncall: releng"]
name: Build Triton wheels

on:
  push:
    branches:
      - main
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - 'ciflow/triton_binaries/*'
    paths:
      - .github/workflows/build-triton-wheel.yml
      - .github/scripts/build_triton_wheel.py
      - .github/ci_commit_pins/triton.txt
      - .ci/docker/ci_commit_pins/triton.txt
      - .ci/docker/ci_commit_pins/triton-xpu.txt
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/build-triton-wheel.yml
      - .github/scripts/build_triton_wheel.py
      - .github/ci_commit_pins/triton.txt
      - .ci/docker/ci_commit_pins/triton.txt
      - .ci/docker/ci_commit_pins/triton-xpu.txt

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  select-runner:
    if: github.repository_owner == 'pytorch'
    uses: ./.github/workflows/_select-release-runner.yml

  build-wheel-cuda:
    if: github.repository_owner == 'pytorch'
    needs: select-runner
    uses: ./.github/workflows/_build-triton-wheel-linux.yml
    secrets: inherit
    with:
      device: "cuda"
      runs_on: ${{ needs.select-runner.outputs.x86 }}
      docker_image: "pytorch/manylinux2_28-builder:cpu"

  build-wheel-rocm:
    if: github.repository_owner == 'pytorch'
    needs: select-runner
    uses: ./.github/workflows/_build-triton-wheel-linux.yml
    secrets: inherit
    with:
      device: "rocm"
      runs_on: ${{ needs.select-runner.outputs.x86 }}
      docker_image: "pytorch/manylinux2_28-builder:rocm7.2"

  build-wheel-xpu:
    if: github.repository_owner == 'pytorch'
    needs: select-runner
    uses: ./.github/workflows/_build-triton-wheel-linux.yml
    secrets: inherit
    with:
      device: "xpu"
      runs_on: ${{ needs.select-runner.outputs.x86 }}
      docker_image: "pytorch/manylinux2_28-builder:cpu"

  upload-wheel-triton:
    needs: [build-wheel-cuda]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_upload-triton-wheel.yml
    secrets: inherit
    with:
      artifact_pattern: triton-wheel-*-cuda-manylinux_2_28_x86_64

  upload-wheel-rocm:
    needs: build-wheel-rocm
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_upload-triton-wheel.yml
    secrets: inherit
    with:
      artifact_pattern: triton-wheel-*-rocm-manylinux_2_28_x86_64

  upload-wheel-xpu:
    needs: [build-wheel-xpu]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_upload-triton-wheel.yml
    secrets: inherit
    with:
      artifact_pattern: triton-wheel-*-xpu-manylinux_2_28_x86_64
